# Generated by Django 5.1.3 on 2024-11-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='file',
            field=models.FileField(default='documents/default_file.pdf', upload_to='documents/', verbose_name='Upload File'),
        ),
    ]
