# Generated by Django 5.1.3 on 2024-11-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natureoftravel',
            name='nature_travel_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nature of Travel'),
        ),
    ]
