# Generated by Django 5.1.3 on 2024-11-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_natureoftravel_nature_travel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natureoftravel',
            name='nature_travel_name',
            field=models.CharField(max_length=100, verbose_name='Nature of Travel'),
        ),
        migrations.AlterField(
            model_name='travelorder',
            name='travel_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Travel Order Number'),
        ),
    ]
