# Generated by Django 5.1.3 on 2024-11-28 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_natureoftravel_nature_travel_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assigntravel',
            unique_together={('employee', 'travelorder')},
        ),
    ]
